# -*- coding: utf-8 -*-
"""ML Classification Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xOX-lkZwxc26uwK_38_HBcyvP_nShYoJ

Customer Churn Prediction using Machine Learning

Objective

Build a supervised machine learning model to predict whether a customer will leave a company (churn) based on customer demographics and service usage.

Target Variable:

Churn (Yes/No)

Features:

Gender
Senior Citizen
Tenure
Monthly Charges
Total Charges
Contract Type
Internet Service
Payment Method
etc.

Import Libraries
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score

from sklearn.preprocessing import LabelEncoder

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report,
    RocCurveDisplay
)

"""Load Dataset"""

df = pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")

print(df.head())
print(df.info())

"""Data Preprocessing

Remove Customer ID
"""

df.drop("customerID", axis=1, inplace=True)

"""Handle Missing Values"""

df["TotalCharges"] = pd.to_numeric(
    df["TotalCharges"],
    errors="coerce"
)

df["TotalCharges"].fillna(
    df["TotalCharges"].median(),
    inplace=True
)

"""Encode Categorical Variables"""

le = LabelEncoder()

for col in df.columns:
    if df[col].dtype == "object":
        df[col] = le.fit_transform(df[col])

"""Feature Selection"""

X = df.drop("Churn", axis=1)
y = df["Churn"]

"""Train-Test Split"""

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

"""Model 1: Logistic Regression"""

lr = LogisticRegression(max_iter=1000)

lr.fit(X_train, y_train)

y_pred_lr = lr.predict(X_test)
y_prob_lr = lr.predict_proba(X_test)[:,1]

"""Model 2: Random Forest"""

rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)
y_prob_rf = rf.predict_proba(X_test)[:,1]

"""Evaluation Function"""

def evaluate_model(y_test, y_pred, y_prob):

    print("Accuracy:",
          accuracy_score(y_test, y_pred))

    print("Precision:",
          precision_score(y_test, y_pred))

    print("Recall:",
          recall_score(y_test, y_pred))

    print("F1 Score:",
          f1_score(y_test, y_pred))

    print("ROC AUC:",
          roc_auc_score(y_test, y_prob))

    print(classification_report(y_test, y_pred))

"""Logistic Regression Results"""

print("Logistic Regression")

evaluate_model(
    y_test,
    y_pred_lr,
    y_prob_lr
)

"""Random Forest Results"""

print("Random Forest")

evaluate_model(
    y_test,
    y_pred_rf,
    y_prob_rf
)

"""Cross Validation

Logistic Regression
"""

lr_cv = cross_val_score(
    lr,
    X,
    y,
    cv=5,
    scoring="accuracy"
)

print("LR CV Accuracy:",
      lr_cv.mean())

"""Random Forest"""

rf_cv = cross_val_score(
    rf,
    X,
    y,
    cv=5,
    scoring="accuracy"
)

print("RF CV Accuracy:",
      rf_cv.mean())

"""ROC Curve"""

RocCurveDisplay.from_estimator(
    lr,
    X_test,
    y_test
)

plt.title("ROC Curve - Logistic Regression")
plt.show()

RocCurveDisplay.from_estimator(
    rf,
    X_test,
    y_test
)

plt.title("ROC Curve - Random Forest")
plt.show()

"""Confusion Matrix"""

cm = confusion_matrix(
    y_test,
    y_pred_rf
)

sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues'
)

plt.title("Confusion Matrix")
plt.show()