# -*- coding: utf-8 -*-
"""Responsible-AI-Model-Interpretation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15479tZ8dUpP2sgGblikTcdJz1NHEPJe1

Import Libraries
"""

# Commented out IPython magic to ensure Python compatibility.
import sys
import shap
if 'google.colab' in sys.modules:
#   %pip install shap lime fairlearn

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

import sys

import shap

# Check if lime is already installed, if not, install it.
# This addresses the ModuleNotFoundError for 'lime'.
try:
    import lime
except ImportError:
    print("The 'lime' package was not found. Attempting to install it now...")
    if 'google.colab' in sys.modules:
#         %pip install lime
    # After installation, attempt to import again
    import lime

# Now import lime.lime_tabular which depends on lime
import lime.lime_tabular

"""Load Dataset"""

import pandas as pd

df = pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")
df.head()

df = pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")

df.head()

df = pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")

df.head()

"""Global Feature Importance"""

importance = model.feature_importances_

feature_imp = pd.DataFrame({
    'Feature': X.columns,
    'Importance': importance
})

feature_imp = feature_imp.sort_values(
    by='Importance',
    ascending=False
)

print(feature_imp.head(10))

plt.figure(figsize=(10,5))

plt.barh(
    feature_imp['Feature'][:10],
    feature_imp['Importance'][:10]
)

plt.title("Top 10 Important Features")
plt.show()

"""SHAP Explainability

### Model Loading and Training Template

This template provides a general structure for loading data, splitting it into training and testing sets, defining a machine learning model, training it, and making predictions.
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

# --- 1. Load Data (if not already loaded) ---
df = pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")

# Assuming you have your feature matrix 'X' and target vector 'y' already prepared.
# Example: df = pd.read_csv('your_data.csv')
X = df.drop('Churn', axis=1)
y = df['Churn']

# Convert categorical features to numerical using one-hot encoding
X = pd.get_dummies(X, drop_first=True)

# --- 2. Split Data into Training and Testing Sets ---
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2, # 20% for testing
    random_state=42 # for reproducibility
)

# --- 3. Define the Model ---
# Replace RandomForestClassifier with your desired model (e.g., LogisticRegression, SVC, etc.)
model = RandomForestClassifier(
    n_estimators=100, # Number of trees in the forest
    random_state=42 # for reproducibility
)

# --- 4. Train the Model ---
print("Training the model...")
model.fit(X_train, y_train)
print("Model training complete.")

# --- 5. Make Predictions ---
print("Making predictions on the test set...")
predictions = model.predict(X_test)

# --- 6. Evaluate the Model (Optional) ---
print("\nClassification Report:")
print(classification_report(y_test, predictions))

# Display the first few predictions
print("\nFirst 5 predictions:")
print(predictions[:5])

"""Shows:

Most influential features

Positive vs negative impact

Overall model behavior

SHAP Force Plot

Interpretation:

Red features increase prediction probability.

Blue features decrease prediction probability.

LIME Local Explanation

Fairness / Bias Analysis
"""

results = pd.DataFrame({
    'Actual': y_test,
    'Predicted': pred,
    'Gender': sensitive
})

for group in results['Gender'].unique():

    subset = results[
        results['Gender']==group
    ]

    acc = (
        subset['Actual']
        ==
        subset['Predicted']
    ).mean()

    print(group, acc)

"""Using Fairlearn

Bias Mitigation

Rebalance Dataset
"""

from sklearn.utils import resample

"""Remove Proxy Features

Remove features strongly correlated with sensitive attributes.

if indirectly introducing bias.

Fairness-Aware Training

Collect More Diverse Data

Ensure:

balanced genders

balanced age groups

balanced regions
"""