# -*- coding: utf-8 -*-
"""Unemployment Analysis with Python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13Hpmpd0Hx4Cl37dByZpBcyKY9OxWl5aK
"""

# ============================================
# Unemployment Analysis with Python
# Author: Somdatta Paul
# ============================================

# Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import zipfile

# Improve plot appearance
sns.set_style("whitegrid")

# ============================================
# LOAD DATASET
# ============================================

zip_file_path = "archive.zip"
# Assuming the CSV inside the zip is named 'Unemployment in India.csv'
# or 'unemployment.csv'. We'll try to find it.
extracted_csv_filename = ""

try:
    # Ensure the zip file exists
    if not os.path.exists(zip_file_path):
        raise FileNotFoundError(f"Zip archive '{zip_file_path}' not found.")

    # Extract the contents of the zip file
    with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
        zip_ref.extractall()
    print(f"Successfully extracted files from '{zip_file_path}'.")

    # List extracted files to find the CSV
    extracted_files_in_dir = [f for f in os.listdir('.') if f.endswith('.csv')]

    if "Unemployment in India.csv" in extracted_files_in_dir:
        extracted_csv_filename = "Unemployment in India.csv"
    elif "unemployment.csv" in extracted_files_in_dir:
        extracted_csv_filename = "unemployment.csv"
    elif extracted_files_in_dir:
        extracted_csv_filename = extracted_files_in_dir[0] # Take the first CSV found
    else:
        raise FileNotFoundError("No CSV file found after extracting the zip archive.")

    print(f"Attempting to read CSV file: '{extracted_csv_filename}'.")

    # Attempt to read the CSV file with various encodings and parsing options
    try:
        df = pd.read_csv(extracted_csv_filename)
    except UnicodeDecodeError:
        df = pd.read_csv(extracted_csv_filename, encoding='latin1')
    except Exception:
        # Fallback to python engine and flexible separator for more robust parsing
        df = pd.read_csv(extracted_csv_filename, encoding='latin1', sep=r'[;,]', engine='python', on_bad_lines='skip')

    print("Dataset Loaded Successfully!\n")

except FileNotFoundError as e:
    print(f"Error: {e}")
    df = pd.DataFrame() # Initialize an empty DataFrame to prevent further KeyErrors
    print("Please ensure the correct zip file and CSV filename are specified.")
except zipfile.BadZipFile:
    print(f"Error: '{zip_file_path}' is not a valid zip file or is corrupted.")
    df = pd.DataFrame()
    print("Please check the zip file.")
except Exception as e:
    print(f"An unexpected error occurred during file loading: {e}")
    df = pd.DataFrame()
    print("Review the file loading parameters.")

# ============================================
# DATASET OVERVIEW
# ============================================

# Add a check here to ensure df is not empty before proceeding
if df.empty:
    print("DataFrame is empty after loading. Skipping further analysis.")
else:
    print("=" * 50)
    print("FIRST 5 ROWS")
    print("=" * 50)
    print(df.head())

    print("\n")

    print("=" * 50)
    print("DATASET INFORMATION")
    print("=" * 50)
    print(df.info())

    print("\n")

    print("=" * 50)
    print("DATASET SHAPE")
    print("=" * 50)
    print("Rows:", df.shape[0])
    print("Columns:", df.shape[1])

    # ============================================
    # CLEAN COLUMN NAMES
    # ============================================

    df.columns = df.columns.str.strip()

    print("\nColumn Names:")
    print(df.columns)

    # ============================================
    # CHECK MISSING VALUES
    # ============================================

    print("\n")
    print("=" * 50)
    print("MISSING VALUES")
    print("=" * 50)
    print(df.isnull().sum())

    # Remove missing values
    df.dropna(inplace=True)

    print("\nMissing values removed successfully!")

    # ============================================
    # DATA STATISTICS
    # ============================================

    print("\n")
    print("=" * 50)
    print("STATISTICAL SUMMARY")
    print("=" * 50)
    print(df.describe())

    # ============================================
    # DATE CONVERSION
    # ============================================

    if "Date" in df.columns:
        df["Date"] = pd.to_datetime(df["Date"], dayfirst=True)

    # ============================================
    # UNEMPLOYMENT RATE ANALYSIS
    # ============================================

    print("\n")
    print("=" * 50)
    print("AVERAGE UNEMPLOYMENT RATE")
    print("=" * 50)

    # Check if the column exists before calculating mean
    if "Estimated Unemployment Rate (%)" in df.columns:
        avg_rate = df["Estimated Unemployment Rate (%)"].mean()
        print(f"Average Unemployment Rate: {avg_rate:.2f}%")
    else:
        print("'Estimated Unemployment Rate (%)' column not found for average calculation.")
        avg_rate = None # Set to None or a default value if column is missing

    # ============================================
    # VISUALIZATION 1
    # UNEMPLOYMENT RATE DISTRIBUTION
    # ============================================

    if "Estimated Unemployment Rate (%)" in df.columns:
        plt.figure(figsize=(10, 6))
        sns.histplot(
            df["Estimated Unemployment Rate (%)"],
            bins=20,
            kde=True
        )

        plt.title("Distribution of Unemployment Rate")
        plt.xlabel("Unemployment Rate (%)")
        plt.ylabel("Count")
        plt.show()
    else:
        print("'Estimated Unemployment Rate (%)' column not found for Visualization 1.")

    # ============================================
    # VISUALIZATION 2
    # UNEMPLOYMENT RATE OVER TIME
    # ============================================

    if "Date" in df.columns and "Estimated Unemployment Rate (%)" in df.columns:

        plt.figure(figsize=(14, 6))

        sns.lineplot(
            data=df,
            x="Date",
            y="Estimated Unemployment Rate (%)"
        )

        plt.title("Unemployment Rate Over Time")
        plt.xlabel("Date")
        plt.ylabel("Unemployment Rate (%)")
        plt.xticks(rotation=45)
        plt.tight_layout()
        plt.show()
    else:
        print("'Date' or 'Estimated Unemployment Rate (%)' column not found for Visualization 2.")

    # ============================================
    # VISUALIZATION 3
    # TOP STATES WITH HIGHEST UNEMPLOYMENT
    # ============================================
    if "Region" in df.columns and "Estimated Unemployment Rate (%)" in df.columns:
        state_unemployment = (
            df.groupby("Region")["Estimated Unemployment Rate (%)"]
            .mean()
            .sort_values(ascending=False)
        )

        plt.figure(figsize=(12, 6))

        state_unemployment.head(10).plot(
            kind="bar"
        )

        plt.title("Top 10 States with Highest Average Unemployment")
        plt.xlabel("State")
        plt.ylabel("Average Unemployment Rate (%)")
        plt.xticks(rotation=45)
        plt.tight_layout()
        plt.show()
    else:
        print("'Region' or 'Estimated Unemployment Rate (%)' column not found for Visualization 3.")

    # ============================================
    # VISUALIZATION 4
    # EMPLOYMENT DISTRIBUTION
    # ============================================

    if "Estimated Employed" in df.columns:
        plt.figure(figsize=(10, 6))

        sns.boxplot(
            x=df["Estimated Employed"]
        )

        plt.title("Distribution of Employed Population")
        plt.show()
    else:
        print("'Estimated Employed' column not found for Visualization 4.")

    # ============================================
    # VISUALIZATION 5
    # LABOUR PARTICIPATION RATE
    # ============================================

    if "Estimated Labour Participation Rate (%)" in df.columns:
        plt.figure(figsize=(10, 6))

        sns.histplot(
            df["Estimated Labour Participation Rate (%)"],
            bins=20,
            kde=True
        )

        plt.title("Labour Participation Rate Distribution")
        plt.xlabel("Labour Participation Rate (%)")
        plt.show()
    else:
        print("'Estimated Labour Participation Rate (%)\' column not found for Visualization 5.")

    # ============================================
    # CORRELATION HEATMAP
    # ============================================

    numeric_df = df.select_dtypes(include=np.number)
    if not numeric_df.empty and len(numeric_df.columns) > 1:
        plt.figure(figsize=(8, 6))

        sns.heatmap(
            numeric_df.corr(),
            annot=True,
            cmap="coolwarm"
        )

        plt.title("Correlation Heatmap")
        plt.tight_layout()
        plt.show()
    else:
        print("Not enough numeric data for Correlation Heatmap.")

    # ============================================
    # COVID IMPACT ANALYSIS
    # ============================================

    if "Date" in df.columns and "Estimated Unemployment Rate (%)" in df.columns:

        covid_data = df[
            (df["Date"] >= "2020-03-01") &
            (df["Date"] <= "2021-12-31")
        ]

        if not covid_data.empty:
            plt.figure(figsize=(14, 6))

            sns.lineplot(
                data=covid_data,
                x="Date",
                y="Estimated Unemployment Rate (%)"
            )

            plt.title("COVID-19 Impact on Unemployment")
            plt.xlabel("Date")
            plt.ylabel("Unemployment Rate (%)")

            plt.xticks(rotation=45)
            plt.tight_layout()
            plt.show()
        else:
            print("No COVID-19 period data found for analysis.")
    else:
        print("'Date' or 'Estimated Unemployment Rate (%)' column not found for COVID Impact Analysis.")

    # ============================================
    # REGION-WISE ANALYSIS
    # ============================================

    if "Region" in df.columns and "Estimated Unemployment Rate (%)" in df.columns:
        print("\n")
        print("=" * 50)
        print("TOP 10 STATES WITH HIGHEST UNEMPLOYMENT")
        print("=" * 50)

        print(state_unemployment.head(10))

        print("\n")

        print("=" * 50)
        print("TOP 10 STATES WITH LOWEST UNEMPLOYMENT")
        print("=" * 50)

        print(state_unemployment.tail(10))
    else:
        print("'Region' or 'Estimated Unemployment Rate (%)' column not found for Region-Wise Analysis.")

    # ============================================
    # SAVE CLEANED DATA
    # ============================================

    df.to_csv(
        "cleaned_unemployment_data.csv",
        index=False
    )

    print("\nCleaned dataset saved successfully!")

    # ============================================
    # FINAL INSIGHTS
    # ============================================

    print("\n")
    print("=" * 50)
    print("PROJECT COMPLETED SUCCESSFULLY")
    print("=" * 50)

    if avg_rate is not None:
        print(f"Average Unemployment Rate: {avg_rate:.2f}%")
    print(f"Total Records Analyzed: {len(df)}")

    print("\nAnalysis Finished.")